# Generated by Django 6.0.6 on 2026-06-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('student', 'Student'), ('early_bird', 'Early Bird')], default='general', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('event', 'tier_type')},
            },
        ),
    ]
