# Generated by Django 6.0.6 on 2026-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end_date_event_end_time_event_is_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_approve_waitlist',
            field=models.BooleanField(default=True, help_text='Automatic vs manual approval'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_waitlist_size',
            field=models.PositiveIntegerField(default=50, help_text='Maximum waiting list size'),
        ),
        migrations.AddField(
            model_name='event',
            name='reservation_timeout',
            field=models.PositiveIntegerField(default=15, help_text='Reservation timeout in minutes'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
