# Generated by Django 6.0.6 on 2026-06-22 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tickettier'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerassignment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('duty', models.CharField(choices=[('registration', 'Registration Desk'), ('entry_gate', 'Entry Gate'), ('security', 'Security Support'), ('parking', 'Parking Assistance'), ('food', 'Food Counter'), ('technical', 'Technical Support'), ('stage', 'Stage Management'), ('helpdesk', 'Help Desk'), ('logistics', 'Logistics')], default='registration', max_length=30)),
                ('shift_timing', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_volunteers', to='events.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
