# Generated by Django 6.0.6 on 2026-06-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_auto_approve_waitlist_event_max_waitlist_size_and_more'),
        ('volunteers', '0003_shift_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvolunteer',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='role',
            field=models.CharField(blank=True, default='Volunteer', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventvolunteer',
            name='duty',
            field=models.CharField(blank=True, choices=[('registration', 'Registration Desk'), ('entry_gate', 'Entry Gate'), ('security', 'Security Support'), ('parking', 'Parking Assistance'), ('food', 'Food Counter'), ('technical', 'Technical Support'), ('stage', 'Stage Management'), ('helpdesk', 'Help Desk'), ('logistics', 'Logistics')], default='registration', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='DutyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_areas', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='duty_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='volunteers.dutyarea'),
        ),
    ]
