# Generated by Django 6.0.6 on 2026-06-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_profile_picture'),
        ('accounts', '0005_alter_customuser_role_organization_apikey_and_more'),
    ]

    operations = [
    ]
