# Generated by Django 6.0.6 on 2026-06-28 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_attendee_notes_booking_badge_printed_and_more'),
        ('events', '0004_event_auto_approve_waitlist_event_max_waitlist_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended')], default='confirmed', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(blank=True, default='', max_length=50)),
                ('gate', models.CharField(blank=True, default='Main Gate', max_length=50)),
                ('device', models.CharField(blank=True, default='Mobile Scanner', max_length=150)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('rejected', 'Rejected')], default='success', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='bookings.booking')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('scanner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
